# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b161de749f019637a0689fb592b4c4b8"
application_url = "https://lumvi.net"
embedded = true
name = "Lumvi"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://lumvi.net/connect/shopify/callback" ]
