"""
blueprints/chat.py
------------------
The core chat pipeline (/api/chat) and the user rating endpoint (/api/chat/rate).

This is the hottest code path in Lumvi — every widget message flows through here.
All behaviour is identical to the original; nothing has been changed except:
  - Route registration: Blueprint vs app
  - app.logger → current_app.logger
  - Inline `import traceback` promoted to module level
  - `_notify_handoff` renamed `notify_handoff` (public, from blueprints.inbox)
  - Rate limits applied after registration via init_chat() — same pattern as leads
  - All dependencies injected at registration time via init_chat()

Routes
------
  POST   /api/chat          chat
  POST   /api/chat/rate     chat_rate

Registration in app.py:
  from blueprints.chat import chat_bp, init_chat
  init_chat(
      limiter=limiter,
      ai_helper=ai_helper,
      plan_limits=PLAN_LIMITS,
      vertical_prompts=VERTICAL_PROMPTS,
      log_conversation=log_conversation,
      find_best_match=find_best_match,
      get_cached_client_owner=_get_cached_client_owner,
      fire_webhook=fire_webhook_event,
      notify_handoff=notify_handoff,
  )
  app.register_blueprint(chat_bp)
  # Re-apply rate limits after blueprint registration
  from blueprints.chat import chat as _chat_view, chat_rate as _chat_rate_view
  limiter.limit("30 per minute")(_chat_view)
  limiter.limit("20 per minute")(_chat_rate_view)
"""

import json
import traceback

from flask import Blueprint, jsonify, request, current_app

import cache_utils
import models
from app_utils import sanitize_input

# ── Blueprint ────────────────────────────────────────────────────────────────

chat_bp = Blueprint('chat', __name__)

# Injected dependencies — populated by init_chat() before first request.
_ai_helper                = None
_plan_limits              = None
_vertical_prompts         = None
_log_conversation         = None
_find_best_match          = None
_get_cached_client_owner  = None
_fire_webhook             = None
_notify_handoff           = None


def init_chat(limiter, ai_helper, plan_limits, vertical_prompts,
              log_conversation, find_best_match, get_cached_client_owner,
              fire_webhook, notify_handoff):
    """
    Called once in app.py after all shared objects are ready.
    limiter is accepted but not stored — rate limits are applied externally
    after blueprint registration (same pattern as leads_bp).
    Must be called before the first request reaches this blueprint.
    """
    global _ai_helper, _plan_limits, _vertical_prompts, _log_conversation, \
            _find_best_match, _get_cached_client_owner, _fire_webhook, _notify_handoff
    _ai_helper               = ai_helper
    _plan_limits             = plan_limits
    _vertical_prompts        = vertical_prompts
    _log_conversation        = log_conversation
    _find_best_match         = find_best_match
    _get_cached_client_owner = get_cached_client_owner
    _fire_webhook            = fire_webhook
    _notify_handoff          = notify_handoff


# ── Routes ───────────────────────────────────────────────────────────────────

@chat_bp.route('/api/chat', methods=['POST'])
def chat():
    try:
        data      = request.json
        message   = sanitize_input(data.get('message', ''))
        client_id = sanitize_input(data.get('client_id', 'demo'), max_length=50)

        # session_id — generated by the widget on first load, stored in localStorage,
        # sent with every message. Ties conversations, session memory, and inbox
        # tickets together into one traceable thread.
        session_id = sanitize_input(data.get('session_id', ''), max_length=100) or None

        if not message:
            return jsonify({'success': False, 'error': 'Message is required'}), 400

        client = None  # always defined — stays None if DB call below fails
        try:
            client = models.get_client_by_id(client_id)
            if not client:
                current_app.logger.warning(
                    f'Client not found: {client_id}, using demo FAQs'
                )
                faqs_list = [
                    {
                        "id": "demo_1",
                        "question": "What are your hours?",
                        "answer": "We're open Monday-Friday, 9 AM - 6 PM EST. Weekend hours: Saturday 10 AM - 4 PM. Closed Sundays. 🕒",
                        "triggers": ["hours", "open", "opening", "closing", "working"]
                    },
                    {
                        "id": "demo_2",
                        "question": "What are your prices?",
                        "answer": "Starter: $49/mo | Pro: $99/mo | Agency: $299/mo. All plans include a 14-day free trial! 💰",
                        "triggers": ["price", "pricing", "cost", "fee", "payment", "charge", "afford", "subscription"]
                    },
                    {
                        "id": "demo_3",
                        "question": "Do you offer discounts?",
                        "answer": "Yes! Annual plans save you 2 full months. Ask us about annual billing. 🎉",
                        "triggers": ["discount", "sale", "promo", "coupon", "deal", "cheaper", "reduce", "saving", "annual"]
                    }
                ]
                config = {}
            else:
                config    = (json.loads(client['branding_settings'])
                             if client['branding_settings'] else {})
                faqs_list = models.get_faqs(client_id)
        except Exception as db_error:
            current_app.logger.error(f'Database error: {db_error}')
            faqs_list = []
            config    = {}

        lead_triggers = config.get('bot_settings', {}).get(
            'lead_triggers', ['contact', 'sales', 'demo', 'speak', 'talk']
        )
        message_lower = message.lower()

        # ── Plan enforcement: messages_per_day (grandfathered plans) or
        # conversations_per_month (new ai_starter/ai_growth/ai_scale tiers) ──
        # Only check for real (non-demo) clients so the demo widget is
        # never accidentally blocked.
        #
        # _chat_daily_limit / _chat_monthly_limit are threaded into every
        # log_conversation call below so the atomic CTE insert can re-check
        # the cap under the same DB snapshot — preventing races at the
        # boundary. Only one of the two is ever set for a given plan —
        # 'conversations_per_month' is a brand-new PLAN_LIMITS key that only
        # exists on ai_starter/ai_growth/ai_scale; every grandfathered plan
        # (solo/starter/pro/growth/agency/enterprise/free) has no such key,
        # so .get() returns None and they fall through to the unchanged
        # daily-message-cap path exactly as before.
        #
        # lead_capture_allowed gates the two lead-trigger points further
        # down. Defaults to True (unrestricted) for demo and for any plan
        # without an explicit 'lead_capture' key — i.e. every grandfathered
        # plan keeps today's behavior (lead capture was never gated before
        # this pivot). Only ai_starter explicitly sets it False.
        _chat_daily_limit    = None  # None == unlimited / demo — no atomic check needed
        _chat_monthly_limit  = None
        lead_capture_allowed = True
        if client and client_id != 'demo':
            owner = _get_cached_client_owner(client_id)
            if owner:
                plan_type    = owner.get('plan_type', 'free')
                plan_limits  = _plan_limits.get(plan_type, _plan_limits['free'])
                lead_capture_allowed = plan_limits.get('lead_capture', True)
                monthly_cap  = plan_limits.get('conversations_per_month', '__unset__')

                if monthly_cap != '__unset__':
                    # ── New tiers: monthly conversation cap ─────────────────
                    if monthly_cap is not None:  # None == unlimited (ai_scale)
                        _chat_monthly_limit = monthly_cap
                        month_count         = models.get_monthly_conversation_count(client_id)
                        if month_count >= monthly_cap:
                            current_app.logger.info(
                                f"[Limit] {client_id} hit monthly cap "
                                f"({month_count}/{monthly_cap}) on plan '{plan_type}'"
                            )
                            return jsonify({
                                'success':       True,
                                'response': (
                                    "You've reached this month's conversation limit. "
                                    "Upgrade your plan for more capacity. 🚀"
                                ),
                                'limit_reached': True,
                                'upgrade_url':   '/upgrade?plan=ai_growth',
                                'method':        'limit_enforced',
                            })
                        elif month_count >= int(monthly_cap * 0.8):
                            pct = round(month_count / monthly_cap * 100)
                            current_app.logger.info(
                                f"[UsageWarning] {client_id} at {pct}% of monthly cap "
                                f"({month_count}/{monthly_cap}) on plan '{plan_type}'"
                            )
                            try:
                                models.upsert_usage_warning(
                                    client_id, pct, month_count, monthly_cap
                                )
                            except Exception:
                                pass  # non-fatal
                else:
                    # ── Grandfathered plans: unchanged daily message cap ────
                    daily_limit = plan_limits['messages_per_day']
                    if daily_limit < 999999:
                        _chat_daily_limit = daily_limit  # thread down to log_conversation
                        today_count       = models.get_daily_message_count(client_id)
                        if today_count >= daily_limit:
                            current_app.logger.info(
                                f"[Limit] {client_id} hit daily cap "
                                f"({today_count}/{daily_limit}) on plan '{plan_type}'"
                            )
                            return jsonify({
                                'success':       True,
                                'response': (
                                    "You've reached today's message limit. "
                                    "Upgrade your plan for unlimited messages, or try again tomorrow. 🚀"
                                ),
                                'limit_reached': True,
                                'upgrade_url':   '/upgrade?plan=ai_growth',
                                'method':        'limit_enforced',
                            })
                        # ── Overage warning: fire at 80% usage ──────────────────
                        elif today_count >= int(daily_limit * 0.8):
                            pct = round(today_count / daily_limit * 100)
                            current_app.logger.info(
                                f"[UsageWarning] {client_id} at {pct}% of daily cap "
                                f"({today_count}/{daily_limit}) on plan '{plan_type}'"
                            )
                            # Continue processing but flag the warning in the response
                            # so the dashboard can show a banner next time the owner logs in.
                            try:
                                models.upsert_usage_warning(
                                    client_id, pct, today_count, daily_limit
                                )
                            except Exception:
                                pass  # non-fatal

        # Load vertical system prompt
        vertical = config.get('vertical', 'general')
        vertical_system_prompt = (
            config.get('bot_settings', {}).get('system_prompt') or
            _vertical_prompts.get(vertical)
        )

        # ── Step 1: Keyword-only lead check (AI disabled path only) ────────
        # When AI is enabled, generate_response() handles lead detection
        # internally as part of the full pipeline — no need to pre-check here.
        # Gated on lead_capture_allowed — ai_starter doesn't include lead
        # capture, so those clients fall straight through to a normal answer
        # instead of being offered the "connect you with our team" prompt.
        if not (_ai_helper and _ai_helper.enabled) and lead_capture_allowed:
            for trigger in lead_triggers:
                if trigger.lower() in message_lower:
                    response_text = (
                        "I'd be happy to connect you with our team! "
                        "What's the best email to reach you?"
                    )
                    _log_conversation(
                        client_id, message, response_text,
                        matched=True, method='lead_trigger',
                        session_id=session_id, daily_limit=_chat_daily_limit, monthly_limit=_chat_monthly_limit,
                    )
                    return jsonify({
                        'success':                 True,
                        'response':                response_text,
                        'trigger_lead_collection': True,
                        'method':                  'lead_trigger',
                        'contact_info':            config.get('contact', {}),
                    })

        # ── Step 2: Full RAG Pipeline ────────────────────────────────────
        if _ai_helper and _ai_helper.enabled:
            try:
                # Load 15-message history — summarisation handled inside generate_response
                convo_history = models.get_recent_conversations(client_id, limit=15)

                current_app.logger.info(
                    f"[Chat] client={client_id} faqs={len(faqs_list)} "
                    f"history={len(convo_history)} vertical={vertical}"
                )

                # ── Fetch kb_version once per request (Redis O(1)) ────────
                # Passed into generate_response so the helper can do cache
                # lookup/write without a second Redis round-trip from app.py.
                # Only fetch for real clients; demo always bypasses cache.
                kb_version = (
                    cache_utils.get_kb_version(client_id)
                    if client_id != 'demo' else None
                )

                # Full pipeline: embed search → rerank → RAG generate → guardrails
                result = _ai_helper.generate_response(
                    user_message          = message,
                    faqs                  = faqs_list,
                    vertical              = vertical,
                    conversation_history  = convo_history,
                    client_id             = client_id,
                    lead_triggers         = lead_triggers,
                    kb_version            = kb_version,
                    session_id            = session_id,
                )

                response_text = result.get('response', '')
                method        = result.get('method', 'rag_pipeline')
                confidence    = result.get('confidence', 0.0)
                from_cache    = result.get('method') == 'cache'

                # ── HANDOFF: contact_request or is_lead from pipeline ─────
                # When the AI returns a contact_request action (IDK, confidence
                # gate, frustration escalation), create a human_inbox ticket
                # immediately — don't wait for the user to fill in a lead form.
                # contact_request handoffs are always allowed (baseline support
                # escalation, not the marketed "Lead capture" feature) — only
                # the is_lead branch is gated on lead_capture_allowed, since
                # ai_starter doesn't include lead capture.
                _action     = result.get('action') or {}
                _is_handoff = (
                    _action.get('type') == 'contact_request' or
                    (result.get('is_lead') and lead_capture_allowed)
                )
                if _is_handoff and client_id != 'demo':
                    _handoff    = result.get('handoff') or {}
                    _sess_mem   = (_handoff.get('session_memory') or
                                   result.get('lead_metadata') or {})
                    _reason     = (
                        _handoff.get('unanswered_question') or
                        message or 'User triggered handoff'
                    )
                    _urgency    = (
                        'high' if _sess_mem.get('frustration_score', 0) >= 3
                        else 'normal'
                    )
                    _transcript = _handoff.get('transcript') or []
                    _summary    = (
                        '\n'.join(
                            f"{t['role'].upper()}: {t['content']}"
                            for t in _transcript[-6:]
                        )
                        if _transcript else message
                    )

                    try:
                        from tools import escalate_to_human as _escalate
                        _ticket = _escalate(
                            client_id      = client_id,
                            session_id     = session_id or '',
                            reason         = _reason[:500],
                            customer_email = _sess_mem.get('email') or '',
                            customer_name  = _sess_mem.get('name')  or '',
                            summary        = _summary[:2000],
                            urgency        = _urgency,
                        )
                        if _ticket.get('success'):
                            _ticket_id = _ticket.get('ticket_id', '')
                            current_app.logger.info(
                                f"[Handoff] ticket={_ticket_id} "
                                f"method={method} client={client_id}"
                            )
                            _notify_handoff(
                                client_id = client_id,
                                client    = client,
                                config    = config,
                                ticket_id = _ticket_id,
                                reason    = _reason,
                                urgency   = _urgency,
                                name      = _sess_mem.get('name')  or '',
                                email     = _sess_mem.get('email') or '',
                                summary   = _summary,
                                method    = method,
                            )
                    except Exception as _esc_err:
                        current_app.logger.warning(
                            f"[Handoff] escalation non-critical: {_esc_err}"
                        )

                    _log_conversation(
                        client_id, message, response_text,
                        matched=True, method=method,
                        session_id=session_id, daily_limit=_chat_daily_limit, monthly_limit=_chat_monthly_limit,
                    )

                    # System 2: collect escalation training sample
                    if client_id != 'demo':
                        try:
                            from training_collector import collect_escalation
                            collect_escalation(
                                client_id    = client_id,
                                session_id   = session_id or '',
                                user_message = message,
                                reason       = _reason,
                                bot_response = response_text,
                                ticket_id    = (str(_ticket_id)
                                                if '_ticket_id' in locals() else ''),
                                urgency      = _urgency,
                                vertical     = vertical,
                            )
                        except Exception as _tc_err:
                            current_app.logger.debug(
                                f'[TrainingCollector] escalation error: {_tc_err}'
                            )

                    return jsonify({
                        'success':                 True,
                        'response':                response_text,
                        'trigger_lead_collection': True,
                        'method':                  method,
                        'contact_info':            config.get('contact', {}),
                        'session_id':              session_id,
                    })

                # Catch any remaining is_lead signals not caught above
                if result.get('is_lead') and lead_capture_allowed:
                    _log_conversation(
                        client_id, message, response_text,
                        matched=True, method='lead_pipeline',
                        session_id=session_id, daily_limit=_chat_daily_limit, monthly_limit=_chat_monthly_limit,
                    )
                    return jsonify({
                        'success':                 True,
                        'response':                response_text,
                        'trigger_lead_collection': True,
                        'method':                  'lead_pipeline',
                        'contact_info':            config.get('contact', {}),
                        'session_id':              session_id,
                    })

                if response_text:
                    matched = confidence > 0.4
                    _log_conversation(
                        client_id, message, response_text,
                        matched=matched, method=method,
                        session_id=session_id, daily_limit=_chat_daily_limit, monthly_limit=_chat_monthly_limit,
                    )

                    # System 2: collect training sample in background
                    if client_id != 'demo':
                        try:
                            from training_collector import collect_conversation_turn
                            collect_conversation_turn(
                                client_id    = client_id,
                                session_id   = session_id or '',
                                user_message = message,
                                bot_response = response_text,
                                method       = method,
                                confidence   = confidence,
                                vertical     = vertical,
                                is_lead      = bool(result.get('is_lead')),
                            )
                        except Exception as _tc_err:
                            current_app.logger.debug(
                                f'[TrainingCollector] chat turn error: {_tc_err}'
                            )

                    current_app.logger.info(
                        f"[AI Match] method={method} confidence={confidence:.2f} "
                        f"response_len={len(response_text)} cached={from_cache}"
                    )

                    # Summarise long conversations non-blocking
                    if not from_cache and client_id != 'demo':
                        try:
                            _ai_helper.maybe_summarise(client_id, convo_history)
                        except Exception as _sum_err:
                            current_app.logger.debug(
                                f"[Summarise] non-critical: {_sum_err}"
                            )

                    # Fire message_sent for every AI response
                    _fire_webhook(client_id, 'message_sent', {
                        'session_id': session_id,
                        'message':    message,
                        'response':   response_text,
                        'method':     method,
                        'confidence': round(confidence, 4),
                    })
                    # Fire faq_matched when AI matched with meaningful confidence
                    if matched and confidence >= 0.5:
                        _fire_webhook(client_id, 'faq_matched', {
                            'session_id': session_id,
                            'message':    message,
                            'response':   response_text,
                            'method':     method,
                            'confidence': round(confidence, 4),
                        })

                    _confirm_replies = (
                        ['Yes, go ahead', 'No, cancel']
                        if method == 'external_action_confirm' else None
                    )

                    return jsonify({
                        'success':    True,
                        'response':   response_text,
                        'confidence': confidence,
                        'method':     method,
                        'session_id': session_id,  # echoed so widget can store it
                        **({'quick_replies': _confirm_replies} if _confirm_replies else {}),
                    })

            except Exception as ai_error:
                current_app.logger.error(
                    f"[RAG Pipeline] error: {ai_error}", exc_info=True
                )

        # ── Step 3: Keyword fallback (threshold=0.68, AI disabled/failed) ──
        best_faq, confidence = _find_best_match(message, faqs_list)
        if best_faq:
            current_app.logger.info(
                f"[Keyword Fallback] faq='{best_faq.get('id')}' "
                f"score={confidence:.3f} threshold=0.68"
            )
            response_text = best_faq.get('answer')
            _log_conversation(
                client_id, message, response_text,
                matched=True, method='keyword_fallback',
                session_id=session_id, daily_limit=_chat_daily_limit, monthly_limit=_chat_monthly_limit,
            )
            _fire_webhook(client_id, 'message_sent', {
                'session_id': session_id,
                'message':    message,
                'response':   response_text,
                'method':     'keyword_fallback',
                'confidence': round(confidence, 4),
            })
            _fire_webhook(client_id, 'faq_matched', {
                'session_id': session_id,
                'message':    message,
                'response':   response_text,
                'method':     'keyword_fallback',
                'confidence': round(confidence, 4),
            })
            return jsonify({
                'success':    True,
                'response':   response_text,
                'confidence': confidence,
                'method':     'keyword_fallback',
            })

        # ── Step 4: Fallback ──────────────────────────────────────────────
        fallback = config.get('bot_settings', {}).get(
            'fallback_message',
            "I'm not sure about that. Would you like to speak with our team? Type 'contact'!"
        )
        _log_conversation(
            client_id, message, fallback,
            matched=False, method='fallback',
            session_id=session_id, daily_limit=_chat_daily_limit, monthly_limit=_chat_monthly_limit,
        )
        return jsonify({
            'success':             True,
            'response':            fallback,
            'confidence':          0.0,
            'show_contact_button': True,
            'method':              'fallback',
        })

    except Exception as e:
        current_app.logger.error(f'Error in chat endpoint: {e}')
        traceback.print_exc()
        return jsonify({'success': False, 'error': 'Internal server error'}), 500


@chat_bp.route('/api/chat/rate', methods=['POST'])
def chat_rate():
    """
    System 2: User thumbs-up (1) / thumbs-down (-1) rating on a bot response.
    Stores a rating training sample and updates the quality on the original sample.

    Body: { client_id, session_id, sample_id, rating, user_message, bot_response }
    rating: 1 = positive, -1 = negative, 0 = neutral
    """
    try:
        data         = request.json or {}
        client_id    = sanitize_input(data.get('client_id', ''),    max_length=50)
        session_id   = sanitize_input(data.get('session_id', ''),   max_length=100)
        sample_id    = sanitize_input(data.get('sample_id', ''),    max_length=30)
        user_message = sanitize_input(data.get('user_message', ''), max_length=1000)
        bot_response = sanitize_input(data.get('bot_response', ''), max_length=2000)

        try:
            rating = int(data.get('rating', 0))
        except (TypeError, ValueError):
            rating = 0
        rating = max(-1, min(rating, 1))

        if not client_id:
            return jsonify({'success': False, 'error': 'client_id required'}), 400

        if client_id != 'demo':
            client = models.get_client_by_id(client_id)
            if not client:
                return jsonify({'success': False, 'error': 'Client not found'}), 404

            from training_collector import collect_user_rating
            collect_user_rating(
                client_id    = client_id,
                session_id   = session_id,
                sample_id    = sample_id,
                rating       = rating,
                user_message = user_message,
                bot_response = bot_response,
            )

        return jsonify({'success': True, 'rating': rating})

    except Exception as e:
        current_app.logger.error(f'[chat/rate] error: {e}')
        return jsonify({'success': False, 'error': 'Internal server error'}), 500
